
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heazyjjosrftwbbhamzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlYXp5ampvc3JmdHdiYmhhbXp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDA5NzksImV4cCI6MjA2MjI3Njk3OX0.68jLGwo5I46ZBNgqq_BsXXb0LwNUBPWLapmb7lu01mQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
